apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: raspi-monitor
  name: raspi-monitor
spec:
  nodeSelector:
    device: knode2
  containers:
    - name: raspi-monitor
      image: ghcr.io/etatsu/raspimonitor:main
      imagePullPolicy: Always
      securityContext:
        privileged: true
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
