name: Deploy RaspiMonitor

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: raspi-monitor
              
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build
          working-directory: ./apps/4_raspiMonitor
          run: |
            docker build -t raspi-monitor -f Dockerfile.monitor .
            docker tag raspi-monitor:latest ${{ github.repository_owner }}/raspi-monitor:latest
  
        - name: Deploy
          working-directory: ./apps/4_raspiMonitor
          run: |
            docker push ${{ github.repository_owner }}/raspi-monitor:latest
