name: Deploy RaspiMonitor

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy
          run: |
            docker build -t raspi-monitor ./apps/4_raspiMonitor/Dockerfile.monitor
            docker tag raspi-monitor:latest ${{ github.repository_owner }}/raspi-monitor:latest
            docker push ghcr.io/${{ github.repository_owner }}/raspi-monitor:latest
