name: Deploy RaspiMonitor

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy
          run: |
            docker build -t raspi-monitor -f Dockerfile.monitor ./apps/4_raspiMonitor/
            docker tag raspi-monitor:latest ${{ github.repository_owner }}/raspi-monitor:latest
            docker push ghcr.io/${{ github.repository_owner }}/raspi-monitor:latest
